"""initial schema

Revision ID: 20aa39d0df9c
Revises: 
Create Date: 2026-07-12 12:32:15.525611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aa39d0df9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('head_employee_id', sa.Integer(), nullable=True),
    sa.Column('parent_dept_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='deptstatus'), nullable=False),
    sa.ForeignKeyConstraint(['head_employee_id'], ['employees.id'], name='fk_dept_head', use_alter=True),
    sa.ForeignKeyConstraint(['parent_dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('available', 'allocated', 'maintenance', 'lost', name='assetstatus'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_tag'), 'assets', ['tag'], unique=True)
    op.create_table('audit_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auditor_ids', sa.JSON(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'asset_manager', 'admin', name='employeerole'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('alert', 'approval', 'booking', 'transfer', 'audit', 'maintenance', name='logtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_type'), 'activity_logs', ['type'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condition_on_return', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_asset_id'), 'allocations', ['asset_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('expected_location', sa.String(length=200), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'missing', 'damaged', name='verificationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['audit_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_cycle_id'), 'audit_records', ['cycle_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=200), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'conflict', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_resource_name'), 'bookings', ['resource_name'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'technician_assigned', 'in_progress', 'resolved', name='maintenancestatus'), nullable=False),
    sa.Column('technician_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_asset_id'), 'maintenance_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_status'), 'maintenance_requests', ['status'], unique=False)
    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_employee_id', sa.Integer(), nullable=False),
    sa.Column('to_employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='transferstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_requests_asset_id'), 'transfer_requests', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_requests_asset_id'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    op.drop_index(op.f('ix_maintenance_requests_status'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_asset_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_bookings_resource_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_records_cycle_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_allocations_asset_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_activity_logs_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('audit_cycles')
    op.drop_index(op.f('ix_assets_tag'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('departments')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
