"""Add multi-day booking support

Revision ID: 5cb844bc54f2
Revises: 128892f2fa74
Create Date: 2026-07-12 15:01:05.162403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb844bc54f2'
down_revision: Union[str, Sequence[str], None] = '128892f2fa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('end_date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.create_index(op.f('ix_bookings_end_date'), 'bookings', ['end_date'], unique=False)
    op.create_index(op.f('ix_bookings_start_date'), 'bookings', ['start_date'], unique=False)
    op.drop_column('bookings', 'date')
    op.create_foreign_key('fk_dept_head', 'departments', 'employees', ['head_employee_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dept_head', 'departments', type_='foreignkey')
    op.add_column('bookings', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bookings_start_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_date'), table_name='bookings')
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.drop_column('bookings', 'end_date')
    op.drop_column('bookings', 'start_date')
    # ### end Alembic commands ###
