"""Add closed_at to audit_cycles

Revision ID: 6d65913cb6f5
Revises: 5cb844bc54f2
Create Date: 2026-07-12 16:06:04.473480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d65913cb6f5'
down_revision: Union[str, Sequence[str], None] = '5cb844bc54f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_cycles', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_cycles', 'closed_at')
    # ### end Alembic commands ###
